### ISSUE TITLE
KeyError: 'next_token'

### ISSUE THREAD

**Issue by viprocket1** [m3yevn/followbot-twitter#1]
Hey, the code ran but after page 3 it gave this error.
```Traceback (most recent call last):
  File "followbot-twitter-master\app.py", line 7, in <module>
    following = get_followings()
  File "followbot-twitter-master\utils\util_funcs.py", line 72, in get_followings
    next_token = result['meta']['next_token']
KeyError: 'next_token'```

**Comment by m3yevn** [comment]
no issue when i follow all the steps on my mac
